db:
  username: default_tenant_user
  password: default_tenant_password
  database: default_tenant

backendApp:
  portalSekolah:
    image: edu-app:latest
    domain: "portal-sekolah-dev.portalsiswa.id"
    replicaCount: 1
    port: 8000
    configMapReference:
      refName: sdn-banjararum-config
      values:
        DJANGO_SETTINGS_MODULE: config.settings.development

frontendApp:
  configMapReference:
    refName: frontend-general-config
    values:
      NEXT_PUBLIC_ENV: "development"
      NEXT_PUBLIC_HOME_URL: "localhost"
      NEXT_PUBLIC_ENDPOINT_URL: "https://backend-v2.portalsiswa.id"
  assesment:
    image: 329599622510.dkr.ecr.ap-southeast-3.amazonaws.com/fe-portalsekolah-assessment-dev
    domain: "assessment-dev.portalsiswa.id"
    replicaCount: 1
    port: 3000
  counseling:
    image: 329599622510.dkr.ecr.ap-southeast-3.amazonaws.com/fe-portalsekolah-counseling-dev
    domain: "counseling-dev.portalsiswa.id"
    replicaCount: 1
    port: 3000

postgresql:
  architecture: standalone
  auth:
    username: default_tenant_user
    password: default_tenant_password
    database: default_tenant
    enablePostgresUser: true
    postgresPassword: postgres

  primary:
    persistence:
      enabled: true
      existingClaim: "pg-storage"
      size: 1Gi

  resources:
    requests:
      memory: 1Gi
      cpu: 1000m
    limits:
      memory: 4Gi
      cpu: 4000m
  # postgres metrics
  metrics:
    enabled: true
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 5
      enabled: true
