{{- if .Values.aws.ecr.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-secret-updater
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-secret-manager
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: ecr-secret-updater
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-ecr-credentials-updater
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.aws.ecr.cronSchedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          serviceAccountName: ecr-secret-updater
          containers:
          - name: ecr-cred-helper
            image: {{ .Values.aws.ecr.helperImage }}
            env:
            - name: AWS_ACCESS_KEY_ID
              value: "{{ .Values.aws.ecr.accessKey }}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "{{ .Values.aws.ecr.secretKey }}"
            - name: AWS_REGION
              value: "{{ .Values.aws.ecr.region }}"
            - name: AWS_ACCOUNT
              value: "{{ .Values.aws.ecr.registryId }}"
            - name: SECRET_NAME
              value: "aws-ecr-credentials"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            command:
            - /bin/sh
            - '-c'
            - |
              set -e
              ECR_TOKEN=$(aws ecr get-login-password --region "${AWS_REGION}" 2>&1)
              
              # Delete existing secret if it exists
              kubectl delete secret --ignore-not-found ${SECRET_NAME} -n ${NAMESPACE}
              
              # Create new secret with fresh token
              kubectl create secret docker-registry ${SECRET_NAME} \
                --docker-server=https://${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com \
                --docker-username=AWS \
                --docker-password="${ECR_TOKEN}" \
                -n ${NAMESPACE}
                
              echo "AWS Region: ${AWS_REGION}"
              echo "Secret name: ${SECRET_NAME}"
              echo "Secret was successfully updated at $(date)"
          restartPolicy: OnFailure
---
# Create initial secret to use until CronJob runs for the first time
apiVersion: v1
kind: Secret
metadata:
  name: aws-ecr-credentials
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s.dkr.ecr.%s.amazonaws.com\":{\"auth\":\"%s\"}}}" .Values.aws.ecr.registryId .Values.aws.ecr.region (printf "AWS:%s" "dummy-token" | b64enc) | b64enc }}
{{- end }}
