---
{{- if .Values.frontendApp.main }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-fe-main
  labels:
    app: {{ .Release.Name }}-app-fe-main

spec:
  replicas: {{ .Values.frontendApp.main.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app-fe-main
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app-fe-main
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/fe-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: frontend-app-main
          image: {{ .Values.frontendApp.main.image }}
          imagePullPolicy: {{ if .Values.aws.ecr.enabled }}Always{{ else }}Never{{ end }}
            {{- if .Values.frontendApp.configMapReference }}
          envFrom:
            - configMapRef:
                name: {{ .Values.frontendApp.configMapReference.refName }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.frontendApp.main.port }}
      {{- if .Values.aws.ecr.enabled }}
      imagePullSecrets:
        - name: aws-ecr-credentials
      {{- end}}
{{- end }}

---
{{- if .Values.frontendApp.assesment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-fe-assessment
  labels:
    app: {{ .Release.Name }}-app-fe-assessment

spec:
  replicas: {{ .Values.frontendApp.assesment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app-fe-assessment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app-fe-assessment
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/fe-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: frontend-app-assessment
          image: {{ .Values.frontendApp.assesment.image }}
          imagePullPolicy: {{ if .Values.aws.ecr.enabled }}Always{{ else }}Never{{ end }}
            {{- if .Values.frontendApp.configMapReference }}
          envFrom:
            - configMapRef:
                name: {{ .Values.frontendApp.configMapReference.refName }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.frontendApp.assesment.port }}
      {{- if .Values.aws.ecr.enabled }}
      imagePullSecrets:
        - name: aws-ecr-credentials
      {{- end}}
{{- end }}

---
{{- if .Values.frontendApp.counseling }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-fe-counseling
  labels:
    app: {{ .Release.Name }}-app-fe-counseling

spec:
  replicas: {{ .Values.frontendApp.counseling.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app-fe-counseling
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app-fe-counseling
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/fe-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: frontend-app-assessment
          image: {{ .Values.frontendApp.counseling.image }}
          imagePullPolicy: {{ if .Values.aws.ecr.enabled }}Always{{ else }}Never{{ end }}
            {{- if .Values.frontendApp.configMapReference }}
          envFrom:
            - configMapRef:
                name: {{ .Values.frontendApp.configMapReference.refName }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.frontendApp.counseling.port }}
      {{- if .Values.aws.ecr.enabled }}
      imagePullSecrets:
        - name: aws-ecr-credentials
      {{- end}}
{{- end }}
