{{- if .Values.frontendApp.assesment }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-fe-assessment
  labels:
    app: {{ .Release.Name }}-service-fe-assessment
spec:
  ports:
    - port: 443
      targetPort: 3000
  selector:
    app: {{ .Release.Name }}-app-fe-assessment
{{- end }}


---
{{- if .Values.frontendApp.counseling }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-fe-counseling
  labels:
    app: {{ .Release.Name }}-service-fe-counseling
spec:
  ports:
    - port: 443
      targetPort: 3000
  selector:
    app: {{ .Release.Name }}-app-fe-counseling
{{- end }}


